import 'package:insta_clone/models/post_model.dart';

List<PostModel> posts = [
  PostModel(
    // authorId: 1,
    authorName: 'nickname123',
    content: '',
    creationDate: DateTime.now(),
    id: 1,
    type: 'video',
    caption:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis blandit turpis a ante iaculis elementum. Vestibulum non mauris quis nulla ultricies vestibulum. Nunc ultrices varius odio, at dignissim nulla cursus ut. Curabitur sollicitudin felis eget tellus semper tempus. Sed euismod tincidunt sagittis. Curabitur faucibus rhoncus enim aliquet bibendum. In hac habitasse platea dictumst.',
    likes: [],
    reposts: 0,
    savedBy: 0,
    sent: 0,
  ),
  PostModel(
    // authorId: 1,
    authorName: 'nickname123',
    content: '',
    creationDate: DateTime.now(),
    id: 2,
    type: 'video',
    caption: 'The Second Post',
    likes: [],
    reposts: 0,
    savedBy: 0,
    sent: 0,
  ),
  PostModel(
    // authorId: 1,
    authorName: 'nickname123',
    content: '',
    creationDate: DateTime.now(),
    id: 3,
    type: 'video',
    caption: 'The Third One',
    likes: [],
    reposts: 0,
    savedBy: 0,
    sent: 0,
  ),
  PostModel(
    // authorId: 1,
    authorName: 'nickname123',
    content: '',
    creationDate: DateTime.now(),
    id: 4,
    type: 'video',
    caption: 'The Fourth!!!!!!!!!!!!!!!',
    likes: [],
    reposts: 0,
    savedBy: 0,
    sent: 0,
  ),
];
